### ISSUE TITLE
Possibility to install on a v0.2 style X carriage?

### ISSUE THREAD

**Issue by gargamel778** [harry-boe/Ghost-LG#1]
I printed the files and assembled the toolhead, I think it looks fantastic. Attached is the built piece.
...I then discovered that I can't use it on my v0.1, because I switched to a mini-SB a short while ago, which uses a different toolhead carriage. 
Any chance the design can be adapted to suit?

![IMG_2152](https://user-images.githubusercontent.com/80474759/230798963-230811af-8360-4d46-9092-73f9e80e4a65.jpeg)

**Comment by harry-boe** [comment]
looks great

the V0.2 mount is fundamentally different than the v0.1 mount.
the steppers motor is raiser by +- 5mm due to the 3rd mount screw from the back 

same for the ghost LG:  the stepper motor needs to raised as well to fit the mount and this will result I a entirely new geometry on the gearbox.

A V0.2 style ghost LG is on the bucket list but will not be ready soon.

**Comment by gargamel778** [comment]
I figured as much. I wish it wasn't that much of a hassle for me to go back to the v0.1 carriage.
My belts are cut flush with the carriage, making any form of maintenance a tedious task...

In the meantime, I'll keep a watch on this project because it's awesome.
